#!/usr/bin/env python3
"""Assemble .claude/tiers/{strong,mid,light}.md from their source fragments.

Why generated rather than hand-written: three packs sharing most of their
content is exactly how a canon fragments -- someone edits one copy, the
others drift, and later models hit contradictions they resolve at random
(DIAGNOSIS.md §II.1). Fragments are the single source; packs are build
output and should never be edited directly.

`--check` verifies the committed packs still match their sources and exits
non-zero if not, so a stale pack fails acceptance instead of shipping.

Exit codes: 0 = built / up to date, 1 = stale (--check), 2 = config error.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TIERS_DIR = REPO_ROOT / ".claude" / "tiers"
MANIFEST = TIERS_DIR / "manifest.json"

BANNER = (
    "<!-- GENERATED by scripts/build-tier-packs.py -- do not edit directly.\n"
    "     Edit the fragments under .claude/tiers/src/ and rebuild.\n"
    "     Sources for this pack: {sources} -->\n"
)


def load_manifest() -> dict:
    try:
        data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"ERROR: missing {MANIFEST.relative_to(REPO_ROOT)}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"ERROR: manifest is not valid JSON: {exc}")
    packs = data.get("packs")
    if not isinstance(packs, dict) or not packs:
        raise SystemExit("ERROR: manifest has no non-empty 'packs' object")
    return data


def render(tier: str, sources: list[str]) -> str:
    parts = [BANNER.format(sources=", ".join(sources))]
    for rel in sources:
        path = REPO_ROOT / rel
        if not path.is_file():
            raise SystemExit(f"ERROR: tier {tier!r} references missing source {rel}")
        parts.append(path.read_text(encoding="utf-8").rstrip() + "\n")
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true",
        help="verify packs match sources; write nothing, exit 1 if stale",
    )
    args = parser.parse_args(argv)

    manifest = load_manifest()
    stale: list[str] = []

    for tier, sources in manifest["packs"].items():
        if not isinstance(sources, list) or not sources:
            raise SystemExit(f"ERROR: tier {tier!r} has no sources")
        expected = render(tier, sources)
        target = TIERS_DIR / f"{tier}.md"
        current = target.read_text(encoding="utf-8") if target.is_file() else None

        if args.check:
            if current != expected:
                stale.append(tier)
                reason = "missing" if current is None else "out of date"
                print(f"STALE {tier}.md ({reason})", file=sys.stderr)
            else:
                print(f"ok    {tier}.md matches its sources")
            continue

        if current == expected:
            print(f"ok    {tier}.md already up to date")
        else:
            target.write_text(expected, encoding="utf-8")
            lines = len(expected.splitlines())
            print(f"built {tier}.md ({lines} lines / {len(expected)} chars) "
                  f"from {len(sources)} fragment(s)")

    if stale:
        print(f"\n{len(stale)} pack(s) stale: {', '.join(stale)}. "
              f"Run: python3 scripts/build-tier-packs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
